 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_GAUSSLEGENDRE_1_10_H_ 
#define model_GAUSSLEGENDRE_1_10_H_ 

namespace model
{

   template<>
   struct GaussLegendre<1,10>
   {
       static Eigen::Matrix<double,2,10> abcsissasAndWeights()
       {
           Eigen::Matrix<double,10,2> aw;
           aw<<1.304673574141435e-02, 3.333567215434410e-02, 
               6.746831665550812e-02, 7.472567457529006e-02, 
               1.602952158504878e-01, 1.095431812579909e-01, 
               2.833023029353765e-01, 1.346333596549982e-01, 
               4.255628305091845e-01, 1.477621123573765e-01, 
               5.744371694908156e-01, 1.477621123573764e-01, 
               7.166976970646235e-01, 1.346333596549985e-01, 
               8.397047841495127e-01, 1.095431812579909e-01, 
               9.325316833444925e-01, 7.472567457529093e-02, 
               9.869532642585861e-01, 3.333567215434389e-02; 
               
       return aw.transpose();
       } 
   }; 
/*************************************************/
} 
#endif 

