 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_GAUSSLEGENDRE_1_1_H_ 
#define model_GAUSSLEGENDRE_1_1_H_ 

namespace model
{

   template<>
   struct GaussLegendre<1,1>
   {
       static Eigen::Matrix<double,2,1> abcsissasAndWeights()
       {
           Eigen::Matrix<double,1,2> aw;
           aw<<5.000000000000000e-01, 1.000000000000000e+00; 
               
       return aw.transpose();
       } 
   }; 
/*************************************************/
} 
#endif 

