 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_INCLUDEGAUSSLEGENDRE_1_H_ 
#define model_INCLUDEGAUSSLEGENDRE_1_H_ 

//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_1.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_2.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_4.h>
#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_8.h>
#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_16.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_32.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_64.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_128.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_256.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_512.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_1024.h>
//#include <model/Quadrature/GaussLegendre/dim1/GaussLegendre_1_2048.h>
 
#endif 

