 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_GAUSSLEGENDRE_1_12_H_ 
#define model_GAUSSLEGENDRE_1_12_H_ 

namespace model
{

   template<>
   struct GaussLegendre<1,12>
   {
       static Eigen::Matrix<double,2,12> abcsissasAndWeights()
       {
           Eigen::Matrix<double,12,2> aw;
           aw<<9.219682876640545e-03, 2.358766819325758e-02, 
               4.794137181476210e-02, 5.346966299764429e-02, 
               1.150486629028473e-01, 8.003916427188010e-02, 
               2.063410228566912e-01, 1.015837133607849e-01, 
               3.160842505009098e-01, 1.167462682697517e-01, 
               4.373832957442654e-01, 1.245735229066791e-01, 
               5.626167042557344e-01, 1.245735229067052e-01, 
               6.839157494990898e-01, 1.167462682691761e-01, 
               7.936589771433085e-01, 1.015837133615332e-01, 
               8.849513370971523e-01, 8.003916427167336e-02, 
               9.520586281852375e-01, 5.346966299765873e-02, 
               9.907803171233593e-01, 2.358766819325609e-02; 
               
       return aw.transpose();
       } 
   }; 
/*************************************************/
} 
#endif 

