 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_GAUSSLEGENDRE_1_7_H_ 
#define model_GAUSSLEGENDRE_1_7_H_ 

namespace model
{

   template<>
   struct GaussLegendre<1,7>
   {
       static Eigen::Matrix<double,2,7> abcsissasAndWeights()
       {
           Eigen::Matrix<double,7,2> aw;
           aw<<2.544604382862031e-02, 6.474248308443485e-02, 
               1.292344072003028e-01, 1.398526957446381e-01, 
               2.970774243113014e-01, 1.909150252525596e-01, 
               5.000000000000000e-01, 2.089795918367346e-01, 
               7.029225756886985e-01, 1.909150252525597e-01, 
               8.707655927996969e-01, 1.398526957446381e-01, 
               9.745539561713792e-01, 6.474248308443482e-02; 
               
       return aw.transpose();
       } 
   }; 
/*************************************************/
} 
#endif 

