 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_INCLUDEGAUSSLEGENDRE_1_H_ 
#define model_INCLUDEGAUSSLEGENDRE_1_H_ 

#include <GaussLegendre_1_1.h>
#include <GaussLegendre_1_2.h>
#include <GaussLegendre_1_3.h>
#include <GaussLegendre_1_4.h>
#include <GaussLegendre_1_5.h>
#include <GaussLegendre_1_6.h>
#include <GaussLegendre_1_7.h>
#include <GaussLegendre_1_8.h>
#include <GaussLegendre_1_10.h>
#include <GaussLegendre_1_12.h>
#include <GaussLegendre_1_14.h>
#include <GaussLegendre_1_16.h>
#include <GaussLegendre_1_20.h>
#include <GaussLegendre_1_24.h>
#include <GaussLegendre_1_28.h>
#include <GaussLegendre_1_32.h>
#include <GaussLegendre_1_40.h>
#include <GaussLegendre_1_48.h>
#include <GaussLegendre_1_56.h>
#include <GaussLegendre_1_64.h>
#include <GaussLegendre_1_80.h>
#include <GaussLegendre_1_96.h>
#include <GaussLegendre_1_112.h>
#include <GaussLegendre_1_128.h>
#include <GaussLegendre_1_160.h>
#include <GaussLegendre_1_192.h>
#include <GaussLegendre_1_224.h>
#include <GaussLegendre_1_256.h>
#include <GaussLegendre_1_320.h>
#include <GaussLegendre_1_384.h>
#include <GaussLegendre_1_448.h>
#include <GaussLegendre_1_512.h>
#include <GaussLegendre_1_640.h>
#include <GaussLegendre_1_768.h>
#include <GaussLegendre_1_896.h>
#include <GaussLegendre_1_1024.h>
#include <GaussLegendre_1_1280.h>
#include <GaussLegendre_1_1536.h>
#include <GaussLegendre_1_1792.h>
#include <GaussLegendre_1_2048.h>

#endif 

