 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_GAUSSLEGENDRE_1_3_H_ 
#define model_GAUSSLEGENDRE_1_3_H_ 

namespace model
{

   template<>
   struct GaussLegendre<1,3>
   {
       static Eigen::Matrix<double,2,3> abcsissasAndWeights()
       {
           Eigen::Matrix<double,3,2> aw;
           aw<<1.127016653792584e-01, 2.777777777777778e-01, 
               5.000000000000000e-01, 4.444444444444445e-01, 
               8.872983346207417e-01, 2.777777777777781e-01; 
               
       return aw.transpose();
       } 
   }; 
/*************************************************/
} 
#endif 

