 /* This file is part of MODEL, the Mechanics Of Defect Evolution Library. 
 * 
 * Copyright (C) 2011 by Giacomo Po <gpo@ucla.edu>. 
 * 
 * model is distributed without any warranty under the 
 * GNU General Public License (GPL) v2 <http://www.gnu.org/licenses/>. 
 */

/*** This file is automatically generated by generateGaussLegendre.cpp ***/
#ifndef model_GAUSSLEGENDRE_1_16_H_ 
#define model_GAUSSLEGENDRE_1_16_H_ 

namespace model
{

   template<>
   struct GaussLegendre<1,16>
   {
       static Eigen::Matrix<double,2,16> abcsissasAndWeights()
       {
           Eigen::Matrix<double,16,2> aw;
           aw<<5.299532504174587e-03, 1.357622970588359e-02, 
               2.771248846338370e-02, 3.112676196928028e-02, 
               6.718439880608401e-02, 4.757925584223523e-02, 
               1.222977958224986e-01, 6.231448562679226e-02, 
               1.910618777986782e-01, 7.479799440828859e-02, 
               2.709916111713864e-01, 8.457825969750113e-02, 
               3.591982246103707e-01, 9.130170752241983e-02, 
               4.524937450811814e-01, 9.472530522760073e-02, 
               5.475062549188188e-01, 9.472530522753216e-02, 
               6.408017753896296e-01, 9.130170752246190e-02, 
               7.290083888286136e-01, 8.457825969750103e-02, 
               8.089381222013219e-01, 7.479799440828847e-02, 
               8.777022041775011e-01, 6.231448562776633e-02, 
               9.328156011939158e-01, 4.757925584124647e-02, 
               9.722875115366161e-01, 3.112676196932454e-02, 
               9.947004674958246e-01, 1.357622970587712e-02; 
               
       return aw.transpose();
       } 
   }; 
/*************************************************/
} 
#endif 

